name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
#CI过程
  build:
    runs-on: ubuntu-latest        #设置运行项目环境——在ubuntu虚拟机中
    steps:                        #执行步骤
    - uses: actions/checkout@v2   #copy一份代码

    - name: Set up Go             #动作名称
      uses: actions/setup-go@v2
      with:
        go-version: 1.17          #设置指定go版本

    - name: Build                 #go语言语法编译
      run: go build -v ./...

    - name: Test                  #go语言test文件
      run: go test -v ./...
#CD过程